User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2022-05-25 15:51:21: Failed to download and store experiments, Class name = b, completed in 1169ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
Error 2022-05-25 15:51:21: Failed to initialize experiments, Class name = b, completed in 1177ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
> conda info --json
> conda info --json
> conda info --json
Error 2022-05-25 15:51:21: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://run-628e4d1f90fcc71bd6d4b0af.domino-compute.svc.cluster.local:80/home/ubuntu/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/ubuntu/.config/Code/User/settings.json')
	at _handleError (/opt/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:838)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound'
}
Error 2022-05-25 15:51:21: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://run-628e4d1f90fcc71bd6d4b0af.domino-compute.svc.cluster.local:80/mnt/data/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/mnt/data/.vscode/settings.json')
	at _handleError (/opt/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:838)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound'
}
Python interpreter path: /opt/conda/bin/python
Starting Jedi Python language engine.
> conda info --json
Error 2022-05-25 15:51:22: Failed to get interpreter information for '/usr/local/bin/python3' [Error: Command failed: "/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"
/bin/sh: 1: /usr/local/bin/python3: not found

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"'
}
Error 2022-05-25 15:51:22: Failed to get interpreter information for '/usr/local/bin/python3' [Error: Command failed: "/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"
/bin/sh: 1: /usr/local/bin/python3: not found

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"'
}
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/data
> conda info --json
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/completion.py
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/completion.py
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/data/practice/prc.py
cwd: /mnt/data
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/data/practice/prc.py
cwd: /mnt/data
Error 2022-05-25 15:51:24: stderr jediProxy Error (stderr) /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

> conda env list
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
##########Linting Output - pylint##########
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/code/practice_1.py
cwd: /mnt/code
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/code/practice_1.py
cwd: /mnt/code
##########Linting Output - pylint##########
