Error 2022-05-25 15:40:28: Failed to download and store experiments, Class name = b, completed in 167ms, has a falsy return value, Arg 1: <argument cannot be serialized for logging>, Return Value: undefined [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
Error 2022-05-25 15:40:28: Effort to download experiments within timeout failed with error [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
Error 2022-05-25 15:40:29: Failed to download and store experiments, Class name = b, completed in 677ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
Error 2022-05-25 15:40:29: Failed to initialize experiments, Class name = b, completed in 678ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 403, Forbidden, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:1403796)
	at H.a._callback.a.callback.a.callback (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:315:20)
	at H.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)]
> conda --version
> pyenv root
> python3.7 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2022-05-25 15:40:30: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://run-628e4d1f90fcc71bd6d4b0af.domino-compute.svc.cluster.local:80/home/ubuntu/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/ubuntu/.config/Code/User/settings.json')
	at _handleError (/opt/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:838)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound'
}
> pyenv root
> pyenv root
> pyenv root
> conda env list
Error 2022-05-25 15:40:32: Failed to get interpreter information for '/usr/local/bin/python3' [Error: Command failed: "/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"
/bin/sh: 1: /usr/local/bin/python3: not found

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"'
}
Error 2022-05-25 15:40:32: Failed to get interpreter information for '/usr/local/bin/python3' [Error: Command failed: "/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"
/bin/sh: 1: /usr/local/bin/python3: not found

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/usr/local/bin/python3" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py" "/home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/interpreterInfo.py"'
}
> pyenv root
Starting Jedi Python language engine.
Python interpreter path: /opt/conda/bin/python
> pyenv root
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> conda info --json
> /opt/conda/bin/python ~/.local/share/code-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> pyenv root
> conda env list
> pyenv root
